### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by jaanos** [DiogenesB/APPR-2018-19#3]
Poročilo ti prevede, tako da sem dodal povezavo na repozitorij za zagovore. Če boš do predstavitve še kaj spreminjal, mi prosim javi, da jo posodobim.

Opazil sem, da se ti na osi y histograma pojavljajo številke v eksponentni notaciji. Temu se lahko izogneš tako, da podatke deliš z ustreznim številom - seveda bo potrebno v oznaki osi podati tudi ustrezno enoto, npr.
```R
ggplot(promet_2017, aes(x=mesec.dostave, y=vrednost.placila/1000)) +
  geom_col() + labs(title="Pregled prometa v letu 2017",
                    x="Mesec", y="Skupni promet (v 1000€)") +
  scale_x_continuous(breaks=1:12, labels=month.abb)
```
Zadnja vrstica poskrbi za to, da dobi vsak mesec svojo oznako (sicer se oznake prikažejo na 2.5 meseca, kar ni najlepše videti). Vektor `month.abb` je vgrajen v R - seveda pa lahko definiraš tudi svojega, npr. s slovenskimi imeni mesecev.

**Comment by DiogenesB** [comment]
Popravljeno. Hvala za pomoč.
