### ISSUE TITLE
Poročilo - prikaz grafov

### ISSUE THREAD

**Issue by DiogenesB** [DiogenesB/APPR-2018-19#4]
Na RStudiu mi grafi delujejo, ko pa poženem Binder, se poročilo sicer zažene in prikaže vse razen grafov.
![image](https://user-images.githubusercontent.com/10290926/51278656-79974600-19db-11e9-8847-dc987330c8d9.png)

**Comment by jaanos** [comment]
Nisem prepričan, zakaj se to zgodi. Zanimivo, da če poženem RStudio v Binderju in tam prevedem poročilo, se grafi prikažejo.

Kakorkoli, pri meni deluje, tako da bom povezavo posodobil na zadnji commit.

**Comment by jaanos** [comment]
Razlog, zakaj se grafi ne prikažejo, so presledki v imenih blokov kode, npr.

https://github.com/DiogenesB/APPR-2018-19/blob/c79202e385ae114425b6fc94990fd30bdffc33fa/projekt.Rmd#L67

Presledkom (pa tudi šumnikom in drugim posebnim znakom) se tukaj torej izogibaj - namesto `promet 2017` torej raje uporabi `promet2017`. Mimogrede, kjer se ti oznake osi v grafu prekrivajo, bi jih bilo dobro zarotirati, ali pa zamenjati osi (glej https://github.com/TomasRode/APPR-2018-19/issues/3#issuecomment-454743425).

**Comment by DiogenesB** [comment]
Popravil imena blokov kode, zdaj deluje.
